Repository MarvinMichel/prapla, pull requests merged in 2021-06, with the labels that each got.

#48 Ms button complexity
  components/RecordButton.vue
  components/Word.vue
  pages/index.vue
  static/icons/Ear.svg
Labels: design, prototyping

#52 Vl result screen
  components/GlobalButton.vue
  components/ProgressCircle.vue
  components/RecordButton.vue
  pages/Complete.vue
  pages/index.vue
  static/icons/Next.svg
Labels: enhancement

#56 added send to back when wrong twice
  components/GlobalButton.vue
  pages/index.vue
Labels: enhancement

#58 Helper functions
  .eslintrc.json
  components/Word.vue
  nuxt.config.js
  pages/Complete.vue
  pages/index.vue
  plugins/README.md
  plugins/recognition.js
  plugins/speech.js
Labels: enhancement

#63 Add image API support
  components/Word.vue
  nuxt.config.js
  package-lock.json
  pages/index.vue
  server-middleware/models/SpeechExercise.js
Labels: enhancement

#73 Ms login auth
  components/GlobalButton.vue
  components/RecordButton.vue
  nuxt.config.js
  package-lock.json
  package.json
  pages/index.vue
  pages/login.vue
  plugins/loginRecognition.js
  plugins/recognition.js
  server-middleware/index.js
  server-middleware/models/User.js
  server-middleware/routes/auth.js
  server-middleware/routes/exercise.js
  server-middleware/routes/user.js
Labels: hosting, prototyping

#82 Add authentication
  middleware/README.md
  middleware/guest.js
  nuxt.config.js
  package-lock.json
  package.json
  pages/index.vue
  pages/login.vue
  plugins/loginRecognition.js
  server-middleware/routes/auth.js
  server-middleware/routes/exercise.js
  server-middleware/routes/user.js
  store/README.md
  store/index.js
Labels: bug, enhancement

#83 Ms auth fix
  README.md
  pages/index.vue
  plugins/loginRecognition.js
  server-middleware/index.js
  server-middleware/routes/auth.js
  server-middleware/routes/exercise.js
  store/index.js
Labels: bug, enhancement

#84 Multi exercise
  components/Complete.vue
  components/VisualExercise.vue
  pages/index.vue
  plugins/loginRecognition.js
  plugins/recognition.js
  plugins/speech.js
  server-middleware/db.js
  server-middleware/index.js
  server-middleware/models/Exercise.js
  server-middleware/models/SpeechExercise.js
  server-middleware/models/User.js
  server-middleware/routes/exercise.js
  static/icons/Check.svg
  static/sounds/feedback_fart.mp3
Labels: enhancement, prototyping
