Repository MarvinMichel/prapla, pull requests merged in 2021-05, with the labels that each got.

#1 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: documentation

#6 Prototype transcriptie test
  css/style.css
  images/mic-on.svg
  index.html
  js/index.js
Labels: prototyping

#17 Transfer to Nuxt
  .babelrc
  .editorconfig
  .gitignore
  README.md
  assets/README.md
  components/Logo.vue
  components/README.md
  components/RecordButton.vue
  components/Word.vue
  css/style.css
  images/mic-on.svg
  index.html
  jest.config.js
  js/index.js
  layouts/README.md
  layouts/default.vue
  middleware/README.md
  nuxt.config.js
  package-lock.json
  package.json
  pages/README.md
  pages/index.vue
  plugins/README.md
  static/README.md
  static/favicon.ico
  store/README.md
  test/Logo.spec.js
Labels: enhancement

#18 Add SpeechSynthesis
  components/Header.vue
  components/README.md
  components/Word.vue
  layouts/README.md
  layouts/default.vue
  nuxt.config.js
  pages/README.md
  pages/index.vue
  vercel.json
Labels: prototyping

#22 Add vector images
  components/Word.vue
  pages/index.vue
  static/hond.svg
  static/kat.svg
  static/vis.svg
  static/vogel.svg
Labels: design

#26 Combine image sound
  pages/index.vue
Labels: prototyping

#27 Create navigation and audio feedback
  pages/index.vue
Labels: prototyping

#32 Set voice to Xander
  components/Word.vue
  pages/index.vue
Labels: prototyping

#33 added icons and styling
  components/Header.vue
  components/RecordButton.vue
  components/Word.vue
  pages/index.vue
  static/icons/Arrow.svg
  static/icons/Listen.svg
  static/icons/Microphone.svg
Labels: design

#44 added clapping
  pages/index.vue
  static/sounds/feedback_clapping.mp3
Labels: enhancement

#45 Process feedback from Yuri
  components/Header.vue
  components/ProgressBar.vue
  components/RecordButton.vue
  components/Word.vue
  layouts/default.vue
  package-lock.json
  package.json
  pages/index.vue
  static/hond.svg
  static/icons/Arrow.svg
Labels: enhancement
